### ISSUE TITLE
Error, token is still working even if the user is deleted manually 

### ISSUE THREAD

**Issue by wahengchang** [firebase/firebase-token-generator-node#17]
we are running the user module(signup , login, logout) on a nodejs server, 

1-token, generated by
 FirebaseTokenGenerator.createToken(
    {uid: uid, some: "arbitrary", data: email});

2-using authWithCustomToken to login user.

3-deleting user from firebase dashboard

4-user can still login by the old token 
userAPI.loginWithToken(token).then(function(authData) { })

**Comment by jwngr** [comment]
In step 3, I assume you mean you are removing the user's data from the Firebase realtime database, right? Removing that data has no effect on the actual token you are using the authenticate.

The token will only become invalidated in two ways:

1. You set the [`expires` option](https://github.com/firebase/firebase-token-generator-node#token-options) when generating the token and that amount of time passes.
2. The secret used to generate the token is revoked. You can do this via the **Secrets** tab of your Firebase dashboard. Note that this will invalidate all tokens which were generated via that secret.

There is currently no way to expire a single token otherwise.
